spring:
  application:
    name: service-registry
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVER_PASSWORD}
      username: user



eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false


