spring:
  application:
    name: service-registry
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true



eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false