spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVER_PASSWORD}
      username: user

logging:
  level:
    root: INFO
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG





