server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
