server:
  port: 8002

spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:order
    username: sa
    password:
  h2.console.enabled: true



  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://user-service:8003/oauth2/jwks
      client:
        registration:
          order-service:
            provider: spring
            client-id: order-service
            client-secret: ${ORDER_SERVICE_PASSWORD}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope: server
        provider:
          spring:
            authorization-uri: http://user-service:8003/oauth2/authorize
            token-uri: http://user-service:8003/oauth2/token
            jwk-set-uri: http://user-service:8003/oauth2/jwks