spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVER_PASSWORD}
      username: user


logging:
  level:
    root: INFO
    org.springframework.security.web.server: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security: DEBUG




