spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native


server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/